spring.profiles.active=prod
server.port=8080
springdoc.swagger-ui.path=/swagger-ui
server.tomcat.threads.max=4
logging.file.name=${data.path}/app.log

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

display.video.ffmpeg.path=ffmpeg
display.video.transcode.timeoutMs=600000
